version: '3.9'

services:
  nginx:
    image: jonasal/nginx-certbot:3
    container_name: m3u8_proxy
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - USE_LOCAL_CA=${USE_LOCAL_CA} # if using development, need to set 1, otherwise 0
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./docker/nginx/conf.d:/etc/nginx/user_conf.d:ro
      - ./share:/etc/nginx/share
    depends_on:
      app: 
        condition: service_started

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: m3u8_app
    restart: always 
    environment:
      - SETTING_MODULE=app.config.staging
      - DOCKER_STATUS=True
      - HOST_SCHEME=${HOST_SCHEME}
      - HOST_NAME=${HOST_NAME}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_REGION_NAME=${S3_REGION_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - ./share/:/home/app/code/static/avatar
    ports:
      - 8000

  postgres:
    image: postgres:15
    container_name: m3u8_fb
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'"]
      interval: 5s
      timeout: 5s
      retries: 1
      start_period: 5s
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: